### ISSUE TITLE
Would like to help.

### ISSUE THREAD

**Issue by GomoSDG** [JumpAttacker/EnsageSharp#6]
Hi

I am looking for a project to help out. Is there some documentation for this project that I can read to start doing something?

**Comment by edosssa** [comment]
was wondering the same thing

**Comment by massina** [comment]
Me too would like to contribute.

**Comment by congcongshang** [comment]
oh, Me too , but my English is too bad.

**Comment by Narender-Dhull** [comment]
Check my profile and help me how to start. I would like to contribute.
